### ISSUE TITLE
vscode support and tests

### ISSUE THREAD

**Issue by default-writer** [Maria-A-P/find___imports___and___parents_dot_childs#1]
I can add vscode IDE support into the project, and reorganize it slighltly to make it closer to standards.

You welcome to take a look closer in cloned repo:

https://github.com/default-writer/find___imports___and___parents_dot_childs

**Comment by Maria-A-P** [comment]
Thank you so much!
That was exactly what I was dreaming of - to see the correct way of organizing a github repo.
It will take some time to look through all the changes.
Thanks again!

**Comment by default-writer** [comment]
no problem, still have some more work in progress to complete
